FROM ubuntu:latest

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND noninteractive\
    SHELL=/bin/bash
RUN apt-get update --yes && \
    # - apt-get upgrade is run to patch known vulnerabilities in apt-get packages as
    #   the ubuntu base image is rebuilt too seldom sometimes (less than once a month)
    apt-get upgrade --yes && \
    apt install --yes --no-install-recommends\
    git\
    wget\
    bash\
    fonts-dejavu-core\
    python3\
    pip\
    curl\
    gnupg2\
    ffmpeg\
    libsm6\
    libxext6\
    python-is-python3\
    openssh-server &&\
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
RUN python -m pip install --upgrade pip
RUN pip install jupyterlab ipywidgets opencv-python-headless traitlets

ADD SD-NoteBook.ipynb /
ADD start.sh /
RUN chmod +x /start.sh
CMD [ "/start.sh" ]